// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEW2FdjhQM_fsl5LIhw7MVZrxm4g3UKYY',
    appId: '1:1088886341534:web:08d113355813e80a20608f',
    messagingSenderId: '1088886341534',
    projectId: 'cubit-85c63',
    authDomain: 'cubit-85c63.firebaseapp.com',
    storageBucket: 'cubit-85c63.firebasestorage.app',
    measurementId: 'G-EKS6DKBTRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3x6qfkKRKOccgtVx9J6Ibw8Frwx6Rhk',
    appId: '1:1088886341534:android:48a91a96d125c30920608f',
    messagingSenderId: '1088886341534',
    projectId: 'cubit-85c63',
    storageBucket: 'cubit-85c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndsiyztO9JwMwzSV2xLWKj7itBdFL4lY',
    appId: '1:1088886341534:ios:5094835e825c8de420608f',
    messagingSenderId: '1088886341534',
    projectId: 'cubit-85c63',
    storageBucket: 'cubit-85c63.firebasestorage.app',
    iosBundleId: 'com.example.cubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndsiyztO9JwMwzSV2xLWKj7itBdFL4lY',
    appId: '1:1088886341534:ios:5094835e825c8de420608f',
    messagingSenderId: '1088886341534',
    projectId: 'cubit-85c63',
    storageBucket: 'cubit-85c63.firebasestorage.app',
    iosBundleId: 'com.example.cubit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEW2FdjhQM_fsl5LIhw7MVZrxm4g3UKYY',
    appId: '1:1088886341534:web:4500b3a9f2f02a7220608f',
    messagingSenderId: '1088886341534',
    projectId: 'cubit-85c63',
    authDomain: 'cubit-85c63.firebaseapp.com',
    storageBucket: 'cubit-85c63.firebasestorage.app',
    measurementId: 'G-657ZRE8CV0',
  );
}
